class CameraConfigurationException(BaseException):
    pass


class ImageCaptureException(BaseException):
    pass


class ImageReadException(BaseException):
    pass


class USBCameraTaskError(BaseException):
    pass


#define USB_CAMERA_NO_ERROR 0x0000
#define USB_CAMERA_USB_CREATE_ERROR 0xFF01
#define USB_CAMERA_USB_SET_CONTEXT_ERROR 0xFF02
#define USB_CAMERA_VR_COMMAND_ERROR 0xFF03
#define USB_CAMERA_USB_VERSION_ERROR 0xFF04
#define USB_CAMERA_BUFFER_ERROR 0xFF05
#define USB_CAMERA_I2C_BIT_ERROR 0xFF0B
#define USB_CAMERA_I2C_NACK_ERROR 0xFF0C
#define USB_CAMERA_I2C_TIMEOUT 0xFF0D
#define USB_CAMERA_USB_TASK_ERROR 0xFF20
#define USB_CAMERA_DATA_OVERFLOW_ERROR 0xFF21
#define USB_CAMERA_DATA_LACK_ERROR 0xFF22
#define USB_CAMERA_FIFO_FULL_ERROR 0xFF23
#define USB_CAMERA_DATA_LEN_ERROR 0xFF24
#define USB_CAMERA_FRAME_INDEX_ERROR 0xFF25
#define USB_CAMERA_USB_TIMEOUT_ERROR 0xFF26
#define USB_CAMERA_READ_EMPTY_ERROR 0xFF30
#define USB_CAMERA_DEL_EMPTY_ERROR 0xFF31
#define USB_CAMERA_SIZE_EXCEED_ERROR 0xFF51
#define USB_USERDATA_ADDR_ERROR 0xFF61
#define USB_USERDATA_LEN_ERROR 0xFF62