device:
  arducam_registers:    # leave blank for defaults
  camera: arducam
  device_id: 0
  frame_height: 480
  frame_width: 640
  init_delay: 1
  init_retry: 10
connection:
  host: http://192.168.50.139:9001
  name: default
  timeout: 10
logging:
  filename: cam.log
  level: info
  log_stdout: false               # Enables logging of sys.out and sys.err
  log_fps: true
processing:
  framerate: 20
  record_video: false
  recording_directory: video
  send_images: false
  send_video: false
  video_filesize: 25.0                 # megabytes
  crop: [ 0, 0, 0, 0 ]     # top, left, bottom, right
  rotation: 0
  image_size:  # width, height (for posted images).  leave lank or comment for no resize
  data_bar_size: 15     # %
  text_pad: 10